# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4680ffdc07db31c07978dbc1f73c9ff0fa52530a222e806d43a9e8a2bc3ab91b159ff3d21cc19d2aede0e37274f5a4add98a106795b21fc6315c1d91c6d5daf4

test:
  secret_key_base: 6c9b4b2e1cb49b67b65ba8164d60c80b915843e30518d891f2e5257ab42be1a6f80cee24f862fb5e2809721233798729e74777bc1c63fb7728c083c18a727d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
